sites:
  # The minimum required site configuration is the site's hostname as the key,
  # and an empty map as a value.
  example1.com: {}
  # If the site is a Wordpress or Drupal site, and you want to create backups
  # for these sites, then you need to provide the app name and the SSH config.
  example2.com:
    app: wordpress
    ssh:
      user: example2user
  # Here is a site with a more detailed SSH config, including optional values.
  example3.com:
    app: wordpress
    ssh:
      user: example3user
      host: ssh.example3.com
      port: 21212
      key_filename: /path/to/key_filename

# SQLite database config
#
# The path to the SQLite database file. SQLite is the only supported DB at this time.
database:
  path: ./tmp/sqlite.db

# Backups config
#
# The filesystem used to store backups. Options are "local" and "s3".
backup:
  filesystem: s3
  bucket: "sitebackup-{site_host}"

# Alternative backup config for local backups.
# backup:
#   filesystem: local
#   path: path/to/backups/dir

# AWS S3 config
#
# Region is used when creating buckets for site backups.
# The access key must have the ability to create buckets and upload files to
# existing buckets.
aws:
  region: us-east-1
  aws_access_key_id: xxxxxxxxxxxxxxxxxxxx
  aws_secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# SMTP config
#
# Used to send notifications. Currently notifications are only sent when a site
# changes from UP to DOWN or vice versa.
mail:
  to: brad@treloardigital.com.au
  from: sitemanager@treloardigital.com.au
  host: smtp.mailtrap.io
  port: 2525
  username: xxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxx
  use_tls: False
